### ISSUE TITLE
Errore in deserializzazione

### ISSUE THREAD

**Issue by IrvinDominin** [FatturaElettronica/FatturaElettronica.Core#22]
In deserializzazione delle fattura elettronica allegata (i dati sono stati resi "dummy") viene restituito l'errore:

> Content cannot be converted to the type System.DateTime. Line 69, position 57.

Analizzando la fattura è presente una data ora consegna pari a:
`<DataOraConsegna>221019-01-21T00:00:00</DataOraConsegna>`

il cui anno è un po' alto :-); considerando che la fattura è stata inoltrata da SdI al nostro sistema, è possibile cambiare il controllo in TryParse per le date (da valutare se per tutte o no).

In allegato la fattura incriminata: [ErroreInDeserialize.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2909485/ErroreInDeserialize.zip)

**Comment by nicolaiarocci** [comment]
In realtà, pensandoci, credo sia corretto sollevare eccezione: non è una data valida per .NET. Se per "saltassimo" silenziosamente l campo, restituiremmo una fattura non uguale all'originale. Lo stesso vale per altri tipi dati (eventualmente) non validi. Per il momento chiudo il ticket.

**Comment by IrvinDominin** [comment]
Capisco l'obiezione, nella fattispecie vi è la sola necessità di leggere alcuni dati della fattura non finalizzata a riscriverla, sarebbe pensabile un settings per stoppare gli errori?

**Comment by IrvinDominin** [comment]
@nicolaiarocci sto ricevendo altre fatture con queste caratteristiche; possiamo implementare un setting per evitare questi errori, così da accettare le fatture inoltrate?
