### ISSUE TITLE
Errore in deserializzazione

### ISSUE THREAD

**Issue by IrvinDominin** [FatturaElettronica/FatturaElettronica.Core#23]
In deserializzazione delle fattura elettronica allegata (i dati sono stati resi "dummy") viene restituito l'errore:

> "Text" è un XmlNodeType non valido. Riga 1, posizione 2308.

Il codice di deserializzazione è il seguente:
```
            var fattura = Fattura.CreateInstance(Instance.Privati);

            try
            {
                using (var r = XmlReader.Create(new MemoryStream(File.ReadAllBytes("C:\\Users\\dominin\\Desktop\\ErroreInDeserialize.xml")), new XmlReaderSettings { IgnoreWhitespace = true, IgnoreComments = true, IgnoreProcessingInstructions = true }))
                {
                    fattura.ReadXml(r);
                }
            }
            catch (Exception ex)
            {
            }

```
Sono presenti diverse fatture che restituiscono l'errore segnalato, validando con AdE e altri validatori risultano corrette. A giudicare dalla linea unica e spazi sembra sia generata come se fosse un tracciato ASCII con output su xml.

Avete già gestito casi simili?
[ErroreInDeserialize.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2905152/ErroreInDeserialize.zip)

**Comment by IrvinDominin** [comment]
> > se riduco il numero di spazi presenti nel nodo funziona correttamente, questo mi ha un po' stupito...
> 
> wow, questo è interessante.
> il limite è **4095** caratteri che probabilmente è la dimensione di qualche buffer interno della classe '**XmlReader**

@nicolaiarocci circa questa problematica sei riuscito a gestirla? Ho ancora il problema con la release 2.0.6.0

**Comment by nicolaiarocci** [comment]
PS: intendevo dire che "gli altri buchi nel file vengono letti correttamente dopo la fix inclusa in v2.0"

**Comment by IrvinDominin** [comment]
Ok, scusa cosa intendi con problema upstream?

Concordo sul fatto che è un problema specifico, e purtroppo ricevo milioni di fatture a settimana e non sono in grado di identificare/contattare il produttore di questa bruttura.

Hai già fatto dei pre-processori da cui partire? O inizio da nuovo?

**Comment by IrvinDominin** [comment]
Purtroppo la mostruosità circola :-(

Ok, procedo in autonomia; chiudo.
