### ISSUE TITLE
Spazi - Errore in deserializzazione

### ISSUE THREAD

**Issue by IrvinDominin** [FatturaElettronica/FatturaElettronica.Core#35]
Sto ricevendo centinaia di fatture con molti spazi vuoti, e continua a verificarsi il problema di seguito:

> > se riduco il numero di spazi presenti nel nodo funziona correttamente, questo mi ha un po' stupito...
> 
> wow, questo è interessante.
> il limite è **4095** caratteri che probabilmente è la dimensione di qualche buffer interno della classe '**XmlReader**

@nicolaiarocci circa questa problematica sei riuscito a gestirla? Ho ancora il problema con la release 2.0.6.0

_Originally posted by @IrvinDominin in https://github.com/FatturaElettronica/FatturaElettronica.Core/issues/23#issuecomment-529532401_

**Comment by IrvinDominin** [comment]
Sì, sto usando la "latest" di FatturaElettronica.Core 2.0.0.0, ma ho ancora l'errore, es. con la fattura in allegato
[7029151a-f285-460d-a7dd-e079e8dd262c_dummy.zip](https://github.com/FatturaElettronica/FatturaElettronica.Core/files/3619606/7029151a-f285-460d-a7dd-e079e8dd262c_dummy.zip)

**Comment by IrvinDominin** [comment]
Ciao, @nicolaiarocci posso fornirti ulteriori info sul tema? Sei riuscito a dare un'occhiata? Probabilmente alcune software house le creano così perchè me ne arrivano continuamente :-(

**Comment by nicolaiarocci** [comment]
Vedi https://github.com/FatturaElettronica/FatturaElettronica.Core/issues/23#issuecomment-540961906
