### ISSUE TITLE
Dipendenza da Newtonsoft.Json con versione specifica (10.0.0.0)

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.Core#5]
Sembra che la versione 0.4.0.0 (scaricata manualmente da nuget) richiede la versione esatta (10.0.0.0) della libreria Newtonsoft.Json.

Questa è l'eccezione che ricevo quando compilo l'eseguibile:

`Non è stato possibile caricare il file o l'assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' o una delle relative dipendenze. La definizione di manifesto dell'assembly specificato non corrisponde al riferimento all'assembly. (Eccezione da HRESULT: 0x80131040)`

Con la versione precedente di FatturaElettronicaCore la 0.2.0.0 non ho mai avuto problemi ad utilizzare l'ultima versione di Newtonsoft.Json, credo sia la 11.0.2.0

**Comment by nicolaiarocci** [comment]
Ciao @gminutillo, ho appena fatto questo test:

- `dotnet new console test`
- `dotnet add package FatturaElettronica`
- `dotnet add package Newtonsoft.Json` (mi ha installato la versione 11 di json.net)
- `dotnet build && dotnet run`

Il codice testato è questo:

```c#
using System;
using FatturaElettronica.Impostazioni;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var f = FatturaElettronica.Fattura.CreateInstance(Instance.Privati);
            Console.WriteLine(f.ToJson());
        }
    }
}
```

Sia FatturaElettronica che Core nel `PackageReference` hanno impostato json.net 10, vero, ma dovrebbero accettare upgrade del package senza problemi. Puoi darmi qualche dettaglio in più per riprodurre il problema?

Aggiungo che senz'altro è ora di aggiornare il riferimento :-)

**Comment by gminutillo** [comment]
ciao @nicolaiarocci , anche a me è sembrato strano.
l'unica cosa che posso aggiungere è che ho aggiunto il riferimento alla Newtonsoft.Json anche nel mio progetto perché la utilizzo anche in altre funzioni del mio codice. Ma prima della versione 0.4.0.0 non ho avuto problemi.

In ogni caso ho risolto il problema gestendo l'evento `AppDomain.CurrentDomain.AssemblyResolve` 'iniettando' a runtime l'assembly corretto.

**Comment by nicolaiarocci** [comment]
ok, chiudo il ticket allora.
