### ISSUE TITLE
Problema di serializzazione XmlOption

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.Core#8]
Ciao, Nonostante l'aggiunta dell'attributo "JsonIgnore", il la proprietà XmlOption continua a venire serializzata.

Per far si che non venga serializzata sarebbe necessario modificare il file "BaseClassSerializable.cs" aggiungendo l'attributo "XmlIgnore" e modificando la proprietà da public a private

```
[XmlIgnore]
[JsonIgnore]
private XmlOptions XmlOptions { get; set; }
```

Ho provato queste modifiche facendo il clone e la soluzione sembra funzionare.

**Comment by nicolaiarocci** [comment]
`XmlOptions` non dovrebbe essere (de)serializzata se per xml e json usi i metodi forniti dalla classe.

**Comment by ardennext99** [comment]
intendi questi metodi()? oFattura.WriteXml() e oFattura.ToJson()?
Questi non sono utili quando si deve persistere su Mongo, perchè serializzando in String si perdono le proprietà dei campi (ad esempio byte[] di Attachment)

se invio a mongoDB una fattura cosi
FatturaList.InsertOne(BsonSerializer.Deserialize(oFattura.ToJson()))
mi ritrovo il campo Allagato salvato così (sbagliato)
"Attachment": "JVBERi0xLjQKJdP0zOEK="

se invece invio così
FatturaList_WRITE.InsertOne(oFattura);
mi ritrovo il campo Allagato salvato cosi (giusto
"Attachment": BinData(0, "JVBERi0xLjQKJdP0zOEK="))

**Comment by nicolaiarocci** [comment]
Quindi il driver mongo non rispetta `JsonIgnore`?

**Comment by ardennext99** [comment]
Per la proprietà XmlOption no, non se la fila di striscio, secondo me utilizza le reflection per identificare il tipo di dato e tradurre il tipo dato della classe in tipo dato mongo, e questo è davvero utile quando vi vanno a comporre le query in linq, se inietto la classe Fattura, posso ricercare applicando filtri su qualsiasi proprietà

**Comment by nicolaiarocci** [comment]
È per questo che vorresti il capo `private` immagino. Ma questo renderebbe la proprietà inutile.

**Comment by ardennext99** [comment]
Esatto, mettendola private (o  anche protected), il driver mongo non la serializza. Per l'utilità si, impedirebbe di poter utilizzare la funzionalità dall'esterno, ma si potrebbe ovviare creando un metodo nel qualle poter passare XmlOption...

```
[XmlIgnore]
[JsonIgnore]
//public XmlOptions XmlOptions { get; set; } //KO
private XmlOptions XmlOptions { get; set; } //OK

public void SetXmlOptions(XmlOptions XmlOptions)
{
this.XmlOptions = XmlOptions;
}
```

**Comment by ardennext99** [comment]
bisogna però ricordarsi di aggiungere anche gli attrubuti alle proprieta "Header" e "Body" per rinominarle

```
using MongoDB.Bson.Serialization.Attributes;
[BsonElementAttribute("FatturaElettronicaHeader")] 
[BsonElementAttribute("FatturaElettronicaBody")]
```

**Comment by nicolaiarocci** [comment]
Con quest'ultimo commento ti riferisci al ticket FatturaElettronica/FatturaElettronica.NET#83?

No, non mettiamo attributi mongo su una classe generica (nè vogliamo prendere una dipendenza dal driver mongo).
